## 设置端口号
#server:
#  port: 8100
#
## mysql
#spring:
#  datasource:
#    #MySQL配置
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://120.79.158.192:3306/mall-sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: root1234
#  cloud:
#    nacos:
#      discovery:
#        ip: 127.0.0.1:8848
#  application:
#    name: mall-coupon
#
## 配置主键id 为自增长
#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
